name: api_manager
version: 0.1.14
homepage: https://github.com/afratul-taohid/api_manager
description: A simple package for manage api request easily with the help of flutter dio api.

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^3.0.9
  connectivity: ^0.4.8+5

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
